train:
    sup:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_460/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_460/text

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            shuffle: True
            is_descending: True
            batches_per_epoch: 4000
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_460/feat_len.scp



valid:
    clean:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                sample_rate: 16000
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/text
                token_type: char
                token_dict: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/char/dev_clean/dict

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            shuffle: False
            is_descending: True
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/feat_len.scp


test:
    clean:
        type: piece.EuterpePieceIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                sample_rate: 16000
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/text
                token_type: char
                token_dict: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/char/test_clean/dict

            batch_size: 1
            shuffle: False
            is_descending: True
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/feat_len.scp
