train:
    sup:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp:
                    - /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_100/feat.scp
                    - /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_360/feat.scp
                text:
                    - /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_100/text
                    - /ahc/work4/heli-qi/euterpe-heli-qi/recipe/speech/librispeech/train_clean_100/asr/transformer/exp/sup_warmup4k/beam_size=16_maxlen_ratio=1/train_clean_360/hypo_text

            batch_frames: 4000000 # 4000000 = 20000 * 200 (200 = 16000 * 0.0125)
            shuffle: True
            is_descending: True
            batches_per_epoch: 4000
            data_len:
                - /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_100/feat_len.scp
                - /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/train_clean_360/feat_len.scp


valid:
    clean:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/text

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            shuffle: False
            is_descending: True
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/dev_clean/feat_len.scp


test:
    clean:
        type: piece.EuterpePieceIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/text

            batch_size: 1
            shuffle: False
            is_descending: True
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/librispeech/data/raw/test_clean/feat_len.scp
