# mkdocs.yml
site_name: Speechain
site_description: Documentation for Speechain Toolkit

repo_url: https://github.com/bagustris/speechain

theme:
  name: "material"
  favicon: img/favicon.ico
  logo: img/speechain_inverted.png

plugins:
  - search
  - autorefs
  - gen-files:
        scripts:
        - scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [speechain, .]

extra_css:
- css/code_select.css

markdown_extensions:
- pymdownx.highlight:
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - handbook.md
  - datasets.md
  - recipes.md
  - asr.md
  - tts.md
  - criterion.md
  - dataset.md
  - iterator.md
  - model.md
  - module.md
  - optim_sche.md
  - tokenizer.md
  - Reference: reference/ 
