train:
    sup:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/text
                token_type: char
                token_dict: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/char/train/dict

            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/feat_len.scp
            batches_per_epoch: 300
            is_descending: True
            shuffle: True

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)



valid:
    dev:
        type: block.EuterpeBlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/text
                token_type: char
                token_dict: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/char/train/dict

            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/feat_len.scp
            is_descending: True
            shuffle: False

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)



test:
    clean:
        type: piece.EuterpePieceIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                feat_scp: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/test/feat.scp
                text: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/test/text
                token_type: char
                token_dict: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/char/train/dict

            shuffle: False

            batch_size: 1