train:
    sup:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_text.SpeechTextDataset
            dataset_conf:
                feat_type: raw
                src_data: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/feat.scp
                tgt_label: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/text

            shuffle: True
            is_descending: True
            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            batches_per_epoch: 300
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/train/feat_len.scp


valid:
    dev:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_text.SpeechTextDataset
            dataset_conf:
                feat_type: raw
                src_data: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/feat.scp
                tgt_label: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/text

            shuffle: False
            is_descending: True
            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/valid/feat_len.scp


test:
    clean:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_text.EuterpeSpeechTextDataset
            dataset_conf:
                feat_type: raw
                src_data: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/test/feat.scp
                tgt_label: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/test/text

            shuffle: False
            is_descending: True
            batch_frames: 250000
            data_len: /ahc/work4/heli-qi/euterpe-heli-qi/datasets/speech/ljspeech/data/raw16000/test/feat_len.scp