### Author: Heli Qi
### Affiliation: NAIST
### Date: 2022.09
# This is a template of data loading configuration on the train-960 dataset of the LibriSpeech corpus
# This configuration fits 4 × Geforce 1080 Ti GPUs with 11GB memory.
# You can modify this configuration according to your computational resource, such as batch_len and ngpu.
# However, you may not be able to reproduce exactly the same performance with different GPU setting.


### --- Reference Zone --- ###
# shared values
valid_set: dev-clean
txt_format: librispeech

# LibriSpeech-specific values
librispeech_train_set: train-clean-100
librispeech_root: datasets/librispeech/data/wav

# LibriTTS-specific values
libritts_train_set: train-clean-360
libritts_root: datasets/libritts/data/wav16000

# batch-related values
batch_len: 1.5e7
### ----------------------- ###


### --- Training Iterator Configuration --- ###
train:
    type: block.BlockIterator
    conf:
        dataset_type: speech_text.SpeechTextDataset
        dataset_conf:
            main_data:
                feat:
                - !ref <librispeech_root>/<librispeech_train_set>/idx2wav
                - !ref <libritts_root>/<libritts_train_set>/idx2wav
                text:
                - !ref <librispeech_root>/<librispeech_train_set>/idx2<txt_format>_text
                - !ref <libritts_root>/<libritts_train_set>/idx2<txt_format>_text

        data_len:
        - !ref <librispeech_root>/<librispeech_train_set>/idx2wav_len
        - !ref <libritts_root>/<libritts_train_set>/idx2wav_len
        shuffle: True
        is_descending: True
        batch_len: !ref <batch_len>

### --- Validation Iterator Configuration --- ###
# Although block.BlockIterator can be used here, it may cause a sudden surge of consumed GPU memory.
# By using abs.Iterator, each GPU process load just one data instance at each validation step which reduces the GPU burden.
# However, abs.Iterator may consume more CPU during validation. Please be careful about it.
valid:
    type: abs.Iterator
    conf:
        dataset_type: speech_text.SpeechTextDataset
        dataset_conf:
            main_data:
                feat: !ref <librispeech_root>/<valid_set>/idx2wav
                text: !ref <librispeech_root>/<valid_set>/idx2<txt_format>_text

        shuffle: False
        data_len: !ref <librispeech_root>/<valid_set>/idx2wav_len
