train:
    sup:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_text.SpeechTextDataset
            dataset_conf:
                feat_type:  wav
                src_data:  /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/train/feat.scp
                tgt_label: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/train/text
                
                

            data_len: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/train/feat_len.scp
            batches_per_epoch: 300
            is_descending: True
            shuffle: True

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)



valid:
    dev:
        type: block.BlockIterator
        conf:
            dataset_type: speech.speech_text.SpeechTextDataset
            dataset_conf:
                feat_type: wav
                src_data: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/valid/feat.scp
                tgt_label: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/valid/text
                

            data_len: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/valid/feat_len.scp
            is_descending: True
            shuffle: False

            batch_frames: 4000000 # 4000000 = 20000 * 200 (16000 * 0.0125)



test:
    clean:
        type: piece.PieceIterator
        conf:
            dataset_type: speech.speech_text.SpeechTextDataset
            dataset_conf:
                feat_type: wav
                src_data: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/test/feat.scp
                tgt_label: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/test/text
                
            
            shuffle: False
            data_len: /your_directory/SpeeChain/datasets/speech_text/ljspeech/data/raw16000/test/feat_len.scp
            is_descending: True
            batch_size: 1