# The configuration of MFCC extraction for MCD evaluation of synthetic utterances.
# It follows the conventional TTS setting: 50ms stft window + 12.5ms stft hopping.
# The sampling rate 'sr' is automatically decided by the target waveform.
# In most of the materials, MCD is calculated on 24-points MFCC features.

# fairseq configuration
n_mfcc: 13
win_length: 0.05
hop_length: 0.0125
#log_base: null
#htk: True
#norm: null

